# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'React-Example' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for React-Example
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift', '8.0.0-beta.6'

  target 'React-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'React-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
